name: Outdated CI


on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/outdated.yml'
      - 'deps.edn'
      - 'shadow-cljs.edn'
      - 'package.json'
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  clojure-cli: latest
  java-version: "17"


jobs:
  outdated:
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    name: Check outdated deps
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.java-version }}
      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: ${{ env.clojure-cli }}
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            cljdeps-${{ runner.os }}-


      - name: Outdated (Clojure)
        run: |
          clojure -M:slf4j-nop:outdated --skip=github-action --skip=pom


      - name: Discord action job digest notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
